AWSTemplateFormatVersion: '2010-09-09'
Description: ResilienceHub Application
Parameters:
  StackIrland:
    Description: Arn for StackIrland
    Type: String
  StackFrankfurt:
    Description: Arn for StackFrankfurt
    Type: String
Resources:
  AppPolicy:
    Type: AWS::ResilienceHub::ResiliencyPolicy
    Properties:
      DataLocationConstraint: AnyLocation
      Policy:
        Software:
          RpoInSecs: 300
          RtoInSecs: 5400
        Hardware:
          RpoInSecs: 1
          RtoInSecs: 1
        AZ:
          RpoInSecs: 1
          RtoInSecs: 1
        Region:
          RpoInSecs: 300
          RtoInSecs: 3600
      PolicyDescription: "Global Mission Critical"
      PolicyName: GlobalMissionCritical
      Tier: MissionCritical
  Application:
    Type: AWS::ResilienceHub::App
    Properties:
      AppAssessmentSchedule: Daily
      AppTemplateBody: '{"resources":[{"logicalResourceId":{"identifier":"Lambda","logicalStackName":"StackFrankfurt","resourceGroupName":null},"type":"AWS::Lambda::Function","name":"healthcheckfunction-1"},{"logicalResourceId":{"identifier":"RestApi","logicalStackName":"StackFrankfurt","resourceGroupName":null},"type":"AWS::ApiGateway::RestApi","name":"apigatewayrestapi-1"},{"logicalResourceId":{"identifier":"RestApi","logicalStackName":"StackIrland","resourceGroupName":null},"type":"AWS::ApiGateway::RestApi","name":"apigatewayrestapi"},{"logicalResourceId":{"identifier":"Lambda","logicalStackName":"StackIrland","resourceGroupName":null},"type":"AWS::Lambda::Function","name":"healthcheckfunction"},{"logicalResourceId":{"identifier":"LambdaDynamo","logicalStackName":"StackFrankfurt","resourceGroupName":null},"type":"AWS::Lambda::Function","name":"dynamodbfunction-1"},{"logicalResourceId":{"identifier":"AlarmTopic","logicalStackName":"StackIrland","resourceGroupName":null},"type":"AWS::SNS::Topic","name":"alarmtopic"},{"logicalResourceId":{"identifier":"DeadLetterTopic","logicalStackName":"StackIrland","resourceGroupName":null},"type":"AWS::SNS::Topic","name":"deadlettertopic"},{"logicalResourceId":{"identifier":"DeadLetterTopic","logicalStackName":"StackFrankfurt","resourceGroupName":null},"type":"AWS::SNS::Topic","name":"deadlettertopic-1"},{"logicalResourceId":{"identifier":"GlobalTable","logicalStackName":"StackIrland","resourceGroupName":null},"type":"AWS::DynamoDB::GlobalTable","name":"dynamodbglobaltable"},{"logicalResourceId":{"identifier":"LambdaDynamo","logicalStackName":"StackIrland","resourceGroupName":null},"type":"AWS::Lambda::Function","name":"dynamodbfunction"},{"logicalResourceId":{"identifier":"AlarmTopic","logicalStackName":"StackFrankfurt","resourceGroupName":null},"type":"AWS::SNS::Topic","name":"alarmtopic-1"}],"appComponents":[{"id":"appcommon","name":"appcommon","type":"AWS::ResilienceHub::AppCommonAppComponent","resourceNames":[]},{"id":"ComputeAppComponent-ApiGatewayRestApi-RestApi","name":"ApiGatewayRestApi-RestApi","type":"AWS::ResilienceHub::ComputeAppComponent","resourceNames":["apigatewayrestapi","apigatewayrestapi-1"]},{"id":"ComputeAppComponent-LambdaFunction-Lambda","name":"LambdaFunction-Lambda-Healthcheck","type":"AWS::ResilienceHub::ComputeAppComponent","resourceNames":["healthcheckfunction","healthcheckfunction-1"]},{"id":"ComputeAppComponent-LambdaFunction-LambdaDynamo","name":"LambdaFunction-Dynamo","type":"AWS::ResilienceHub::ComputeAppComponent","resourceNames":["dynamodbfunction","dynamodbfunction-1"]},{"id":"NotificationAppComponent-SNSTopic-AlarmTopic","name":"SNSTopic-AlarmTopic","type":"AWS::ResilienceHub::NotificationAppComponent","resourceNames":["alarmtopic","alarmtopic-1"]},{"id":"NotificationAppComponent-SNSTopic-DeadLetterTopic","name":"SNSTopic-DeadLetterTopic","type":"AWS::ResilienceHub::NotificationAppComponent","resourceNames":["deadlettertopic","deadlettertopic-1"]},{"id":"DatabaseAppComponent-DynamoDBTable-GlobalTable","name":"DatabaseAppComponent-DynamoDBTable-GlobalTable","type":"AWS::ResilienceHub::DatabaseAppComponent","resourceNames":["dynamodbglobaltable"]}],"excludedResources":{"logicalResourceIds":[]},"version":2.0}'
      Description: lambda-vpc
      Name: lambda-vpc
      ResiliencyPolicyArn: !Ref 'AppPolicy'
      ResourceMappings:
        - LogicalStackName: 'StackIrland'
          MappingType: CfnStack
          PhysicalResourceId:
            Identifier: !Ref 'StackIrland'
            Type: Arn
            AwsRegion: eu-west-1
            AwsAccountId: !Ref "AWS::AccountId"
        - LogicalStackName: 'StackFrankfurt'
          MappingType: CfnStack
          PhysicalResourceId:
            Identifier: !Ref 'StackFrankfurt'
            Type: Arn
            AwsRegion: eu-central-1
            AwsAccountId: !Ref "AWS::AccountId"
Metadata: {}
Outputs:
  Application:
    Value: !Ref Application
